- name: Prometheus Node Exporter | Download, unzip, and install binary
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    validate_certs: yes
    creates: /usr/bin/prometheus-node-exporter
    extra_opts: [--strip-components=1]

- name: Prometheus Node Exporter | Copy binary to correct place
  command: cp /tmp/node_exporter /usr/bin/prometheus-node-exporter
  args:
    creates: /usr/bin/prometheus-node-exporter

- name: Prometheus Node Exporter | Set binary permissions
  file:
    path: /usr/bin/prometheus-node-exporter
    mode: 0755

- name: Prometheus Node Exporter | Set systemd file
  copy:
    src: prometheus-node-exporter.service
    dest: /etc/systemd/system/prometheus-node-exporter.service

- name: Prometheus Node Exporter | Reload systemd for new service file
  systemd:
    daemon_reload: yes

- name: Prometheus Node Exporter | Enable service in systemd
  systemd:
    name: prometheus-node-exporter
    enabled: yes
