#Regular users
- name: Users | Create user
  user:
    name: "{{ item }}"
    shell: /bin/bash
    createhome: yes
    groups: ["sudo"]
    home: "/home/{{ item }}"
    append: yes
  with_items: "{{ user_list }}"
  when: user_list is defined
