- name: Users | Create admin user
  user:
    name: "clintjedwards"
    shell: /bin/bash
    createhome: yes
    groups: ["sudo"]
    home: "/home/clintjedwards"
    append: yes

- name: Set authorized keys as github keys
  authorized_key:
    user: "clintjedwards"
    state: present
    key: "https://github.com/clintjedwards.keys"
