- name: CoreDNS | Create user
  user:
    name: "coredns"
    createhome: no
    append: yes

- name: CoreDNS | Create /etc/coredns folder
  file:
    path: /etc/coredns
    state: directory
    owner: coredns
    group: coredns

- name: CoreDNS | Create /etc/coredns/zones folder
  file:
    path: /etc/coredns/zones
    state: directory
    owner: coredns
    group: coredns

- name: CoreDNS | Download, unzip, and install binary
  unarchive:
    src: https://github.com/coredns/coredns/releases/download/v{{coredns_version}}/coredns_{{coredns_version}}_linux_arm.tgz
    dest: /usr/bin
    remote_src: yes
    validate_certs: yes
    creates: /usr/bin/coredns
    mode: 0755

- name: CoreDNS | Set systemd file
  copy:
    src: coredns.service
    dest: /etc/systemd/system/coredns.service
  notify: CoreDNS | Restart service

- name: CoreDNS | Reload systemd for new service file
  systemd:
    daemon_reload: yes

- name: CoreDNS | Enable service in systemd
  systemd:
    name: coredns
    enabled: yes

- name: CoreDNS | Set capabilities
  capabilities:
    path: /usr/bin/coredns
    capability: cap_net_bind_service+ep
    state: present

- name: CoreDNS | Copy config files
  copy:
    src: Corefile
    dest: /etc/coredns/Corefile
    owner: coredns
    group: coredns
  notify: CoreDNS | Restart service

- name: CoreDNS | Copy zone files
  copy:
    src: zones/
    dest: /etc/coredns/zones
    owner: coredns
    group: coredns
  notify: CoreDNS | Restart service
