scrape_configs:
  - job_name: "defaults"
    static_configs:
      - targets: [
            # node exporter
            "rpitemp.clintjedwards.home:9100",
            "nas.clintjedwards.home:9100",
            "traefik.clintjedwards.home:9100",
            "prometheus.clintjedwards.home:9100",
            "dns.clintjedwards.home:9100",
            "unifi.clintjedwards.home:9100",
            # apartment temp metrics
            "rpitemp.clintjedwards.home:8001",
            # basecoat service metrics
            "basecoat.clintjedwards.com:4444",
            # coredns metrics
            dns.clintjedwards.home:8001,
          ]
  - job_name: "blackbox"
    metrics_path: "/probe"
    params:
      module: ["http_2xx_ssl"]
    static_configs:
      #List of targets to poll
      - targets:
          - https://basecoat.clintjedwards.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115 # The blackbox exporter's real hostname:port.
