- name: Prometheus Grafana | Create user
  user:
    name: "grafana"
    createhome: no
    append: yes

- name: Prometheus Grafana | Install packages
  apt:
    name: ["sqlite"]
    state: present

- name: Prometheus Grafana | Create /etc/grafana folder
  file:
    path: /etc/grafana
    owner: grafana
    group: grafana
    state: directory
    mode: 0755
    recurse: yes

- name: Prometheus Grafana | Copy config file
  copy:
    src: grafana.ini
    dest: /etc/grafana/
    owner: grafana
    group: grafana

- name: Prometheus Grafana | Install deb package
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.4.5_amd64.deb

- name: Prometheus Grafana | Enable service in systemd
  systemd:
    name: grafana-server
    enabled: yes
