- name: Traefik | Create user
  user:
    name: "traefik"
    createhome: no
    append: yes

- name: Traefik | Create /etc/traefik folder
  file:
    path: /etc/traefik
    state: directory
    owner: traefik
    group: traefik

- name: Traefik | Download, unzip, and install binary
  unarchive:
    src: https://github.com/containous/traefik/releases/download/v{{traefik_version}}/traefik_v{{traefik_version}}_linux_amd64.tar.gz
    dest: /usr/bin
    remote_src: yes
    validate_certs: yes
    creates: /usr/bin/traefik
    mode: 0755

- name: Traefik | Set systemd file
  copy:
    src: traefik.service
    dest: /etc/systemd/system/traefik.service

- name: Traefik | Reload systemd for new service file
  systemd:
    daemon_reload: yes

- name: Traefik | Enable service in systemd
  systemd:
    name: traefik
    enabled: yes

- name: Traefik | Set capabilities
  capabilities:
    path: /usr/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Traefik | Copy config files
  copy:
    src: traefik.toml
    dest: /etc/traefik/traefik.toml
    owner: traefik
    group: traefik
