#Examples and Documentation:
#https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
#https://github.com/prometheus/blackbox_exporter/blob/master/example.yml
modules:
  #Prober for 2xx requests that support TLS
  http_2xx_ssl:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [] # Defaults to 2xx
      preferred_ip_protocol: "ip4"
      method: GET
      headers:
        Accept-Language: en-US
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
